### ISSUE TITLE
how to clear disk cache?

### ISSUE THREAD

**Issue by bravekingzhang** [danikula/AndroidVideoCache#103]

**Comment by jpage4500** [comment]
I'm also wondering how to clear the cache.. is this possible?

My use case is - I want to cache videos while a user is at a certain event (facebook like stream of media during the event). But, after they leave that event I'd like to clear the cache since there's no need to keep these videos around.

**Comment by bravekingzhang** [comment]
@jpage4500  
try
```java
@Click(R.id.cleanCacheButton)
    void onClearCacheButtonClick() {
        try {
            Utils.cleanDirectory(getExternalCacheDir());
        } catch (IOException e) {
            Log.e(null, "Error cleaning cache", e);
            Toast.makeText(this, "Error cleaning cache", Toast.LENGTH_LONG).show();
        }
    }
```

**Comment by jpage4500** [comment]
@bravekingzhang 

I assume this method just deletes all files in the directory? I'm pretty sure I don't see a Utils class in this library

```
Utils.cleanDirectory(getExternalCacheDir());
```

I was looking for something a little more targeted to just the video files that were being cached locally. But, ultimately I ended up making a small change to add in custom logic for keeping/removing cached files - it's in a pull request here: https://github.com/danikula/AndroidVideoCache/pull/106

**Comment by bravekingzhang** [comment]
@jpage4500 That's great ！Thanks for you contribution！

**Comment by danikula** [comment]
@bravekingzhang You can sent cache's directory in `HttpProxyCacheServer.Builder` and then just clean it.

**Comment by pravynandas** [comment]
From com.danikula.videocache.StorageUtils.java, it is clear that the cache director can be internal or external. In my case it is at "/storage/emulated/0/Android/data/com.my.package.name/cache/video-cache". Since the class is not accessible publicly, I copied it to my local module and fetched the cache director. And once it's know deleting it can be straight forward as indicated above. Not sure what is 'Utils.' class here though.
