### ISSUE TITLE
Doesn't work with long URLs

### ISSUE THREAD

**Issue by mightyfrog** [danikula/AndroidVideoCache#14]
Cache file name exceeds the file system's maximum length.

**Comment by danikula** [comment]
@mightyfrog Can you provide example of url that cause this problem?

**Comment by mightyfrog** [comment]
I found the issue while playing a video from vid.me. All the vidoes from vid.me have a URL like this:

https://d1wst0behutosd.cloudfront.net/videos/4367900/10807247.480p.mp4?Expires=1442849176&Signature=JXV~3AoI0rWcGuZBywg3-ukf6Ycw2X8v7Htog3lyvuFwp8o6VUEDFUsTC9-XtIGu-ULxCd7dP3fvB306lRyGFxdvf-sXLX~ar~HCQ7lullNyeLtp8BJOT5Y~W5rJE7X-AZaueNcycGtLFRhRtr5ySTguwtmJNaO3T1apX~-oVrFh1dWStEKbuPoXY04RgkmhMHoFgtwgXMC1ctIDeQHxZeXLi6LLyZnQsgzlUDffCx4P16iiW0uh2-Z~HUOi9BLBwHMQ5k5lYwZqdQ6DhhYoWlniRfQz6mp1IEiMgr4L3Z1ijgGITV4cYeF31CmFzCxaJTE7IIAC5tMDQSTt7M9Q4A__&Key-Pair-Id=APKAJJ6WELAPEP47UKWQ

Md5FileNameGenerator generates a long file name so I made my own by subclassing FileNameGenerator. It appeared working first but I found buffering not working and exiting app clears cache :(

*the above link probably doesn't work as it requires a session or something but I think you can reproduce the issue with the orange video from sample by appending a very long query string to it.

**Comment by danikula** [comment]
@mightyfrog [fixed](https://github.com/danikula/AndroidVideoCache/commit/f4b9e5c8f507550590f4be950ed4e722efd66a33) in 2.1.1
Please, update your projects. 
Thanks for contributing.

**Comment by mightyfrog** [comment]
Wow, that was quick. Thanks.

**Comment by danikula** [comment]
@mightyfrog One important note. If url contain some dynamic data like a session token `AndroidVideoCache` will not work correctly, because it doesn't know that these urls point to the same video. For example you have 2 urls : `http://videos.com/video.mp4?token=abc` and `http://videos.com/video.mp4?token=xyz` . Urls are **different** but point to **same** video `video.mp4`. In this case `AndroidVideoCache` will cache it **twice**! To  prevent it you have to implement your `FileNameGenerator`.
