### ISSUE TITLE
What is the player cache logic?

### ISSUE THREAD

**Issue by lzyang187** [danikula/AndroidVideoCache#143]
Hello, It's not in the player to download, it will cost the user double network flow?

**Comment by danikula** [comment]
Library starts `ServerSocket` at `localhost:SOME_PORT`. Your player should use `proxied url` (see README) instead of  original http url. This local proxy server is responsible for downloading,  caching data from network and providing data for your player. Network monitor can show double traffic, because your player streams data from `http://localhost` and also library fetch data from real http url.
