### ISSUE TITLE
Add information about licensing

### ISSUE THREAD

**Issue by vbauer** [danikula/AndroidVideoCache#2]

**Comment by danikula** [comment]
[fixed](https://github.com/danikula/AndroidVideoCache/commit/8ac1a2d9704d69bebf6e030c49c0d78714e9997b)

**Comment by vbauer** [comment]
Thank you!

**Comment by FstTeam** [comment]
hi. i play video, and in OnCompletionListener event i play other video
videoview.setOnCompletionListener(new OnCompletionListener() {

				@Override
				public void onCompletion(final MediaPlayer mp) {
					// TODO Auto-generated method stub
				
						videoview.setVideoPath(proxyCache.getUrl());
						videoview.setZOrderOnTop(false);
						videoview.requestFocus();
						videoview.setKeepScreenOn(true);
						videoview.start();
					
				}
			});
. I see 1 exception:
05-13 06:07:12.330: E/ProxyCache(21949): ProxyCache error
05-13 06:07:12.330: E/ProxyCache(21949): com.danikula.videocache.ProxyCacheException: Error processing request
05-13 06:07:12.330: E/ProxyCache(21949): 	at com.danikula.videocache.HttpProxyCache.processSocket(HttpProxyCache.java:139)
05-13 06:07:12.330: E/ProxyCache(21949): 	at com.danikula.videocache.HttpProxyCache.access$1(HttpProxyCache.java:131)
05-13 06:07:12.330: E/ProxyCache(21949): 	at com.danikula.videocache.HttpProxyCache$1.run(HttpProxyCache.java:123)
05-13 06:07:12.330: E/ProxyCache(21949): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
05-13 06:07:12.330: E/ProxyCache(21949): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
05-13 06:07:12.330: E/ProxyCache(21949): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
05-13 06:07:12.330: E/ProxyCache(21949): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
05-13 06:07:12.330: E/ProxyCache(21949): 	at java.lang.Thread.run(Thread.java:856)
05-13 06:07:12.330: E/ProxyCache(21949): Caused by: java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)
05-13 06:07:12.330: E/ProxyCache(21949): 	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:506)
05-13 06:07:12.330: E/ProxyCache(21949): 	at libcore.io.IoBridge.sendto(IoBridge.java:475)
05-13 06:07:12.330: E/ProxyCache(21949): 	at java.net.PlainSocketImpl.write(PlainSocketImpl.java:507)
05-13 06:07:12.330: E/ProxyCache(21949): 	at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
05-13 06:07:12.330: E/ProxyCache(21949): 	at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:269)
05-13 06:07:12.330: E/ProxyCache(21949): 	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:131)
05-13 06:07:12.330: E/ProxyCache(21949): 	at com.danikula.videocache.HttpProxyCache.writeResponse(HttpProxyCache.java:157)
05-13 06:07:12.330: E/ProxyCache(21949): 	at com.danikula.videocache.HttpProxyCache.processSocket(HttpProxyCache.java:137)
05-13 06:07:12.330: E/ProxyCache(21949): 	... 7 more
05-13 06:07:12.330: E/ProxyCache(21949): Caused by: libcore.io.ErrnoException: sendto failed: ECONNRESET (Connection reset by peer)
05-13 06:07:12.330: E/ProxyCache(21949): 	at libcore.io.Posix.sendtoBytes(Native Method)
05-13 06:07:12.330: E/ProxyCache(21949): 	at libcore.io.Posix.sendto(Posix.java:151)
05-13 06:07:12.330: E/ProxyCache(21949): 	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
05-13 06:07:12.330: E/ProxyCache(21949): 	at libcore.io.IoBridge.sendto(IoBridge.java:473)
05-13 06:07:12.330: E/ProxyCache(21949): 	... 13 more
