### ISSUE TITLE
Forward http headers from clients to server

### ISSUE THREAD

**Issue by danikula** [danikula/AndroidVideoCache#20]

**Comment by lucas34** [comment]
Hi,

In order to use your library I need this feature.
Let me throw idea on this post.

Structure like follow
Topic
- Prop 1
- Prop 2

Goal : Passing simple parameters in the header for the request to the server.

Header structure.
- Create our own Header class (Maybe be redondant with other libs)
- Use a simple "Map<String, String>". 

How to inject 
- Inside the builder (cannot modify base on url but easier to implement)
- Having a callback before each request with the url and return an array of headers.

I prefer the second one because it gives more flexibility.
We can add on the builder something like 

`java 
builder.addHeadersInjector(new HeaderInjector() {
   @Override 
    Map<String, String> inject(String url) {
          return createMyHeaderForThisUrl(url);
    }
})
`

When to call 
- Only call when the request is done against the real (online) server.
- All the time

Headers conflict 
- The library should override the headers injected by the client.

Feel free to comment or throw more ideas. 
Lucas.

**Comment by danikula** [comment]
@lucas34 this is a great plan! It should really be implemented this way. Can you make PR?

**Comment by danikula** [comment]
Also we must write tests to check 
+ are headers really added to http request?
+ does library override custom headers?
+ null HeaderInjector isn't accepted in builder

Also we should use empty implementation of `HeaderInjector` to avoid null checks.

**Comment by danikula** [comment]
lucas34 [implementation](https://github.com/lucas34/AndroidVideoCache/commit/14e0c336f642bc5952dee4a75035374ede33bbd6) is a good start point.

**Comment by danikula** [comment]
I [merged](https://github.com/danikula/AndroidVideoCache/commit/acdf747a991739204e32e0fde5c893490cfb4e40) @lucas34 implementation to the master. Will be available in `2.8.0`
