### ISSUE TITLE
The method builder() is undefined for the type VideoFragment

### ISSUE THREAD

**Issue by Wendell-Sir** [danikula/AndroidVideoCache#65]
Hi! 
I use eclipse to run your sample.EveryThing is fine except VideoFragment can not find the builder() method:
```
VideoFragment.builder().url(url).cachePath(cachePath).build();
```

**Comment by metalurgus** [comment]
If you want to use a VideoFragment.java from the sample app, then it does not have a method `build()`. It does have` build(Context context, Video video)` and `build(String url, String cachePath)` methods, which have parameters instead of builder-like initialization. See [first](https://github.com/danikula/AndroidVideoCache/blob/master/sample/src/main/java/com/danikula/videocache/sample/VideoFragment.java#L35) and [second](https://github.com/danikula/AndroidVideoCache/blob/master/sample/src/main/java/com/danikula/videocache/sample/VideoFragment.java#L35) methods

**Comment by danikula** [comment]
@Wendell-Sir sample app uses [AndroidAnnotations](http://androidannotations.org/) library. It uses pre-compilation process for generating class `VideoFragment_`. If you don't use gradle as build system you should setup precompiler in eclipse.
