### ISSUE TITLE
AndroidVideoCache can not response seek event

### ISSUE THREAD

**Issue by legendzhouqiang** [danikula/AndroidVideoCache#9]
when i use AndroidVideoCache in my project  ,when i seek the seekbar the mediapalyer stop paly.but if do not add androidVideocache ,when if seek the seekbar ,the mediaplyer is still play and response the seekCompleteListener. what should i do to solve this problem?

**Comment by danikula** [comment]
Right. It is expected behaviour. VideoCache downloads video consequentially. And even if you seek to position that VideoCache havn't achieved yet MediaPlayer wait for achieving this position by VideoCache. 
This behaviour allows to simplify realization. I can suggest you 3 ways:
1. fork project, extend it and make pull request 
2. just show downloading progress with help of `[CacheListener](https://github.com/danikula/AndroidVideoCache/blob/master/library/src/main/java/com/danikula/videocache/CacheListener.java)`. It doesn't solve problem, but shows to user that everything is OK and player just waiting for downloading.
3. Do not use library at all.

**Comment by legendzhouqiang** [comment]
if in my project  video playing url from p2p ,while video download url from other. how to resolve ?

**Comment by danikula** [comment]
ProxyCache support only direct urls with `url://` and `file://` scheme
