### ISSUE TITLE
Add custom headers

### ISSUE THREAD

**Issue by lucas34** [danikula/AndroidVideoCache#90]
Hi,

I would like to discuss about the implementation of the custom headers. The ticket about this issue has already been closed. #20 . Should we create a new one (This one) or re-open the issue #20 ?

Thanks.

**Comment by danikula** [comment]
@lucas34 I closed [46](https://github.com/danikula/AndroidVideoCache/issues/46) because it duplicates [20](https://github.com/danikula/AndroidVideoCache/issues/20). [46](https://github.com/danikula/AndroidVideoCache/issues/46) is still opened so let's discuss it in  [20](https://github.com/danikula/AndroidVideoCache/issues/20). Please close this issue.

**Comment by lucas34** [comment]
Alright
